# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    identifier: wj-yxaEn
    url: /
    weight: 10
  - name: Research
    identifier: R8nxOs71
    url: /#research
    weight: 20
  - name: Publications
    identifier: 6QVJthgY
    url: /#papers
    weight: 30
  - name: Talks
    identifier: uXCjb0iV
    url: /#talks
    weight: 40
